export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS'
export const FETCH_PEOPLE_ERROR = 'FETCH_PEOPLE_ERROR'

export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS'
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR'

export const FETCH_MUSIC_SUCCESS = 'FETCH_MUSIC_SUCCESS'
export const FETCH_MUSIC_ERROR = 'FETCH_MUSIC_ERROR'

export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS'
export const FETCH_DOCUMENTS_ERROR = 'FETCH_DOCUMENTS_ERROR'

export const FETCH_SCIENCE_SUCCESS = 'FETCH_SCIENCE_SUCCESS'
export const FETCH_SCIENCE_ERROR = 'FETCH_SCIENCE_ERROR'
