
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_ERROR = "FETCH_USER_ERROR"
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR"
export const USER_REGISTRATION_CALL = "USER_REGISTRATION_CALL"
export const USER_LOGOUT = "USER_LOGOUT"
export const LS_USER = "LS_USER"
export const USER_CHANGE_EMAIL = 'USER_CHANGE_EMAIL'
export const USER_CHANGE_CONFIRM_TOKEN = "USER_CHANGE_CONFIRM_TOKEN"

export const LOCALE_STORAGE_CONGIRM_TOKEN = "LOCALE_STORAGE_CONGIRM_TOKEN"

